# Generated by Django 5.2.4 on 2026-03-18 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_paid_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='preferred_barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_clients', to='barber.barber'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='preferred_style',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='profile_notes',
            field=models.TextField(blank=True),
        ),
    ]
